{% set tpl = ix_lib.base.render.Render(values) %}

{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set mariadb_config = {
  "user": values.consts.db_user,
  "root_password": values.romm.db_root_password,
  "password": values.romm.db_password,
  "database": values.consts.db_name,
  "volume": values.storage.mariadb_data,
} %}
{% set mariadb_container = tpl.deps.mariadb(values.consts.mariadb_container_name, "mariadb_image", mariadb_config, perm_container) %}

{% set c1 = tpl.add_container(values.consts.romm_container_name, "image") %}
{% do c1.add_caps(["CHOWN", "SETGID", "SETUID"]) %}
{% do c1.depends.add_dependency(values.consts.mariadb_container_name, "service_healthy") %}

{% do c1.set_user(0, 0) %}
{% do c1.add_storage("/root/.romm/resources", values.storage.romm_resources) %}
{% do c1.add_storage("/root/.romm/redis", values.storage.romm_redis_data) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
{% endfor %}

{% do c1.ports.add_port(values.network.web_port, values.consts.internal_web_port) %}

{% do c1.environment.add_env("DB_HOST", values.consts.mariadb_container_name) %}
{% do c1.environment.add_env("DB_PORT", values.romm.db_port) %}
{% do c1.environment.add_env("DB_USER", values.romm.db_user) %}
{% do c1.environment.add_env("DB_PASS", values.romm.db_password) %}
{% do c1.environment.add_env("DB_NAME", values.romm.db_name) %}
{% do c1.environment.add_env("ROMM_AUTH_SECRET_KEY", values.romm.romm_auth_secret_key) %}
{% do c1.environment.add_env("IGDB_CLIENT_ID", values.romm.igdb_client_id) %}
{% do c1.environment.add_env("IGDB_CLIENT_SECRET", values.romm.igdb_client_secret) %}
{% do c1.environment.add_env("MOBYGAMES_API_KEY", values.romm.mobygames_api_key) %}
{% do c1.environment.add_env("STEAMGRIDDB_API_KEY", values.romm.steamgriddb_api_key) %}
{% do c1.environment.add_user_envs(values.romm.additional_envs) %}

{% do c1.healthcheck.set_test("http", {"port": values.consts.internal_web_port, "path": "/favicon-32x32.png"}) %}
{% do tpl.portals.add_portal({"port": values.network.web_port}) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do mariadb_container.container.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.notes.set_body(values.consts.notes_body) %}

{{ tpl.render() | tojson }}

