romm:
  db_port: 3306
  db_name: romm
  db_user: romm
  db_password: mariadb-password
  db_root_password: mariadb-root-password
  romm_auth_secret_key: romm-auth-secret-key
  igdb_client_id: igdb-client-id
  igdb_client_secret: igdb-client-secret
  mobygames_api_key: mobygames-api-key
  steamgriddb_api_key: steamgriddb-api-key
  additional_envs: []

network:
  web_port: 33982
  host_network: false

ix_volumes:
  mariadb_data: /opt/tests/mnt/romm-db
  romm_resources: /opt/tests/mnt/romm-resources
  romm_redis_data: /opt/tests/mnt/romm-redis

run_as:
  user: 568
  group: 568

storage:
  mariadb_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: mariadb_data
      create_host_path: true
  romm_resources:
    type: ix_volume
    ix_volume_config:
      dataset_name: romm_resources
      create_host_path: true
  romm_redis_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: romm_redis_data
      create_host_path: true
  additional_storage: []
